# Server
server.port=8080

# Application
spring.application.name=blockchain-api

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASS:redis123}

# Jackson
spring.jackson.serialization.write-dates-as-timestamps=false

# Services
services.transaction-pool.url=${TRANSACTION_POOL_URL:http://localhost:8082}

# Logging
logging.level.com.blockchain=DEBUG