apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator
  namespace: blockchain-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      nodeSelector:
        pool: apps
      containers:
        - name: coordinator
          image: us-central1-docker.pkg.dev/sdypp-rocco/blockchain-repo/coordinator:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: REDIS_HOST
              value: "redis.blockchain-infra.svc.cluster.local"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: REDIS_PASS
            - name: RABBITMQ_HOST
              value: "rabbitmq.blockchain-infra.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_USER
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secret
                  key: RABBITMQ_PASS
            - name: MINING_PREFIX
              value: "000"
            - name: MINING_CHUNK_COUNT
              value: "2"
            - name: BLOCKCHAIN_API_URL
              value: "http://blockchain-api:8080"
          readinessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: coordinator
  namespace: blockchain-apps
spec:
  selector:
    app: coordinator
  ports:
    - port: 8081
      targetPort: 8081
