server.port=8081
spring.application.name=coordinator

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASS:redis123}

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin123}

# Minería
mining.prefix=${MINING_PREFIX:000}
mining.reward=50.0
mining.range-size=10000000

# Servicios
services.blockchain-api.url=${BLOCKCHAIN_API_URL:http://localhost:8080}

logging.level.com.blockchain=DEBUG