server.port=8083
spring.application.name=worker

# RabbitMQ
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASS:admin123}

# Worker
worker.id=${WORKER_ID:worker-1}
worker.threads=${WORKER_THREADS:8}

logging.level.com.blockchain=DEBUG